fix: ASC-2826 - allow user to update displayName & discription
AmityCo/Amity-Social-Cloud-UIKit-Web-OpenSource pull request #7
Opened 2022-07-26 07:41 UTC by Cijin

### Checklist

- [ ] There is an associated JIRA issue (**required**)
- [ ] The title of your PR is formatted properly (**required**)
- [ ] Code is up-to-date with the `develop` branch (**required**)

- [ ] You've successfully run your unit tests locally
- [ ] There are new or updated unit tests validating the change

### Short description
* fix:change default avatarFileId from empty to null

* Reason: the sdk validation will fail if avatarFileId is empty
* Which leads to an undesirable result where user cannot update
  description or displayName if there is no avatarFileId set

* feat:add util to filter dirty values from form

* feat:filter out dirtyValues from UserProfileForm

* Update src/helpers/utils.js

Co-authored-by: Pawarit (Nhui) Chongkrichug <nightwsh58@gmail.com>

* chore: asc-2826 remove dirtyValues helper

Co-authored-by: Pawarit (Nhui) Chongkrichug <nightwsh58@gmail.com>

2022-07-26 07:57 UTC, serhii-ivanenko-amity requested changes

2022-07-26 07:57 UTC, serhii-ivanenko-amity commented on src/social/components/UserProfileForm/index.js
> +  return -(
not sure if this char should be here

2022-07-26 08:30 UTC, serhii-ivanenko-amity submitted a review, later dismissed

2022-07-26 09:56 UTC, serhii-ivanenko-amity requested changes

2022-07-26 09:56 UTC, serhii-ivanenko-amity commented on .github/workflows/dev.yaml
> +      NPM_FONT_AWESOME_TOKEN: ${{ secrets.NPM_FONT_AWESOME_TOKEN }}
we do not need this one here. It's open source ui-kit, it not use font awesome

2022-07-26 09:56 UTC, serhii-ivanenko-amity commented on .github/workflows/dev.yaml
> -      STORYBOOK_API_ENDPOINT: ${{ secrets.STORYBOOK_API_ENDPOINT }}
why this removed ?

2022-07-26 09:56 UTC, serhii-ivanenko-amity commented on .github/workflows/staging.yaml
> +      NPM_FONT_AWESOME_TOKEN: ${{ secrets.NPM_FONT_AWESOME_TOKEN }}
same

2022-07-26 09:56 UTC, serhii-ivanenko-amity commented on .github/workflows/staging.yaml
> -      STORYBOOK_API_ENDPOINT: ${{ secrets.STORYBOOK_API_ENDPOINT }}
same

2022-07-26 09:56 UTC, serhii-ivanenko-amity commented on src/core/providers/UiKitProvider/index.js
> -  apiEndpoint: PropTypes.string.isRequired,
why this not required ? is there any default value ?

2022-07-26 10:29 UTC, Cijin commented
Is this the reason for failing action?
https://github.com/actions/runner/discussions/1380

2022-07-26 11:00 UTC, Va1tra commented on .github/workflows/dev.yaml
> -      STORYBOOK_API_ENDPOINT: ${{ secrets.STORYBOOK_API_ENDPOINT }}
The recommended way to configure the endpoint is to set the region.

2022-07-27 04:56 UTC, serhii-ivanenko-amity approved these changes, later dismissed

2022-07-27 09:58 UTC, closed without merging